# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # TODO build and lint job

  # Deploys application using the Vercel CLI
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Setup node
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install

      - name: Pull Staging Secrets
        env:
          BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
        run: (echo $BW_PASSWORD && cat) | npm run secrets-staging

      # Deploy using Vercel CLI
      - name: Vercel Deployment
        id: deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "\
            ::set-output name=DEPLOY_LINK::$( \
              (npx vercel --confirm --token $VERCEL_TOKEN >> out.log); \
              cat out.log | egrep -o 'https:\/\/bgc-safety-f2021-.+-bitsofgood.vercel.app' \
            )\
          "
          echo "::set-output name=DEPLOY_TIMESTAMP::$(date +'%Y-%m-%dT%H:%M:%S')"

      # Comment deployment link on PRs
      - name: Comment Deployment on PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ format('### ⚡ [Deployment live]({0}) :zap:', steps.deploy.outputs.DEPLOY_LINK) }}

      # Link deployment to GitHub Preview Environment (for main branch only)
      - name: Create GitHub Deployment for Preview
        if: github.event_name == 'push' && github.head_ref == 'main'
        uses: chrnorm/deployment-action@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ steps.deploy.outputs.DEPLOY_LINK }}
          environment: preview

      # Link deployment to GitHub Production Environment (for production branch only)
      - name: Create GitHub Deployment for Production
        if: github.event_name == 'push' && github.head_ref == 'main'
        uses: chrnorm/deployment-action@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ steps.deploy.outputs.DEPLOY_LINK }}
          environment: Production
